services:
  steve-certi-db:
    # Pinning MariaDB to point release 10.4.30 works around the issues with the
    # database migrations seen with 10.4.31 in issue #1212.
    #
    # TODO: Get database migrations to work with the latest point releases of
    # MariaDB 10.4.
    build:
      dockerfile: docker/Dockerfile.db
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: changeme

  steve-app:
    build: 
      dockerfile: docker/Dockerfile.app
    volumes:
      - ./:/code
    ports:
      - "8180:8180"
      - "8443:8443"
    entrypoint: /code/scripts/run-entrypoint.sh

  webserver-noauth:
   build:
       context: webserver
       dockerfile: Dockerfile
   ports:
     - "80:80"
     - "443:443"
   env_file:
     - ./webserver/webserver_variables.env
   entrypoint: /webserver/webserver-entrypoint.sh
   restart: unless-stopped

  steve-certi-swagger-ui:
    build:
      context: ./steve-certi-docs
      dockerfile: Dockerfile
    environment:
      - BASE_URL="/docs"
    ports:
      - 8080:8080